spring.application.name=service1
spring.datasource.url=jdbc:postgresql://localhost:5432/user_authentication
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
server.servlet.context-path=/api
jwt.secret=y1r3k4m1s4t0k4qwyiq52683hagsdr$!#@#^67zr2365N&@#R^^b2r5
# Enable debug logging for Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web=DEBUG